In [ ]:
# import libraries
from cryptography.fernet import Fernet
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import copy

In [ ]:
# open the key file
with open('filekey.key', 'rb') as f:
    key = f.read()

In [ ]:
# Create the object
fernet = Fernet(key)

In [ ]:
# open the datasets
with open('customer_profile.csv', 'rb') as f:
    customer_profile = f.read()
with open('transaction_data.csv', 'rb') as f:
    transaction_data = f.read()

In [ ]:
# decrypt the data
decrypt_customer_profile = fernet.decrypt(customer_profile)
decrypt_transaction_data = fernet.decrypt(transaction_data)

In [ ]:
# Overwrite the encrypted data with decryption
with open('customer_profile.csv', 'wb') as f:
    f.write(decrypt_customer_profile)
with open('transaction_data.csv', 'wb') as f:
    f.write(decrypt_transaction_data)

In [ ]:
# load the datasets with pandas
customer_profile = pd.read_csv('customer_profile.csv')
transaction_data = pd.read_csv('transaction_data.csv')

In [ ]:
# check whether you are able to see the first 5 rows of the datasets
customer_profile.head()

,Customer_ID,Name,Age,Gender,Location,Membership_Tier,First_Visit_Date,Avg_Monthly_Visits,Communication_Preference,NPS_Score
0,C001,Saurabh Rao,42,F,Delhi,Gold,2021-11-09,10,WhatsApp,0
1,C002,Isha Gupta,26,F,Mumbai,Gold,2024-04-20,9,SMS,3
2,C003,Rohit Joshi,25,F,Bengaluru,Silver,2021-06-13,7,Email,4
3,C004,Rahul Roy,48,F,Bengaluru,Bronze,2021-07-29,4,SMS,9
4,C005,Karan Mehta,53,F,Bengaluru,Gold,2020-10-03,1,Email,5

In [ ]:
transaction_data.head()

,Customer_ID,Last_Purchase_Date,Total_Spend (₹),Marketing_Spend (₹),Purchases_Last_12M,Avg_Order_Value (₹),Campaign_Responded
0,C001,2024-02-08,33617,1003,62,542.21,No
1,C002,2024-08-21,62295,3814,61,1021.23,Yes
2,C003,2024-06-05,65423,1490,54,1211.54,No
3,C004,2024-01-18,21962,6485,37,593.57,Yes
4,C005,2024-05-30,75991,4426,87,873.46,No

In [ ]:
# See the shape of customer_profile data
customer_profile.shape

(200, 10)

In [ ]:
# see the shape of transaction_data
transaction_data.shape

(200, 7)

In [ ]:
# merge the two datasets
marketing_analytics = pd.merge(customer_profile, transaction_data, on='Customer_ID')
marketing_analytics.head()

,Customer_ID,Name,Age,Gender,Location,Membership_Tier,First_Visit_Date,Avg_Monthly_Visits,Communication_Preference,NPS_Score,Last_Purchase_Date,Total_Spend (₹),Marketing_Spend (₹),Purchases_Last_12M,Avg_Order_Value (₹),Campaign_Responded
0,C001,Saurabh Rao,42,F,Delhi,Gold,2021-11-09,10,WhatsApp,0,2024-02-08,33617,1003,62,542.21,No
1,C002,Isha Gupta,26,F,Mumbai,Gold,2024-04-20,9,SMS,3,2024-08-21,62295,3814,61,1021.23,Yes
2,C003,Rohit Joshi,25,F,Bengaluru,Silver,2021-06-13,7,Email,4,2024-06-05,65423,1490,54,1211.54,No
3,C004,Rahul Roy,48,F,Bengaluru,Bronze,2021-07-29,4,SMS,9,2024-01-18,21962,6485,37,593.57,Yes
4,C005,Karan Mehta,53,F,Bengaluru,Gold,2020-10-03,1,Email,5,2024-05-30,75991,4426,87,873.46,No

In [ ]:
# See the shape of marketing_analytics data
marketing_analytics.shape

(200, 16)

In [ ]:
# see the datatypes of the column
marketing_analytics.dtypes

Customer_ID                  object
Name                         object
Age                           int64
Gender                       object
Location                     object
Membership_Tier              object
First_Visit_Date             object
Avg_Monthly_Visits            int64
Communication_Preference     object
NPS_Score                     int64
Last_Purchase_Date           object
Total_Spend (₹)               int64
Marketing_Spend (₹)           int64
Purchases_Last_12M            int64
Avg_Order_Value (₹)         float64
Campaign_Responded           object
dtype: object

In [ ]:
# Check whether the data has any duplicate records of not
duplicate_records = marketing_analytics.duplicated().sum()
print("The number of duplicate records in the dataset is:", duplicate_records)

The number of duplicate records in the dataset is: 0

In [ ]:
# Check whether the datsset has any missing values
missing_values = marketing_analytics.isna().sum()
print("The number of missing values in the dataset is:", missing_values)

The number of missing values in the dataset is: Customer_ID                 0
Name                        0
Age                         0
Gender                      0
Location                    0
Membership_Tier             0
First_Visit_Date            0
Avg_Monthly_Visits          0
Communication_Preference    0
NPS_Score                   0
Last_Purchase_Date          0
Total_Spend (₹)             0
Marketing_Spend (₹)         0
Purchases_Last_12M          0
Avg_Order_Value (₹)         0
Campaign_Responded          0
dtype: int64

In [ ]:
# make the copy of the marketing_analytics data
marketing_analytics_copy = marketing_analytics.copy(deep = True)
marketing_analytics_copy.head()

,Customer_ID,Name,Age,Gender,Location,Membership_Tier,First_Visit_Date,Avg_Monthly_Visits,Communication_Preference,NPS_Score,Last_Purchase_Date,Total_Spend (₹),Marketing_Spend (₹),Purchases_Last_12M,Avg_Order_Value (₹),Campaign_Responded
0,C001,Saurabh Rao,42,F,Delhi,Gold,2021-11-09,10,WhatsApp,0,2024-02-08,33617,1003,62,542.21,No
1,C002,Isha Gupta,26,F,Mumbai,Gold,2024-04-20,9,SMS,3,2024-08-21,62295,3814,61,1021.23,Yes
2,C003,Rohit Joshi,25,F,Bengaluru,Silver,2021-06-13,7,Email,4,2024-06-05,65423,1490,54,1211.54,No
3,C004,Rahul Roy,48,F,Bengaluru,Bronze,2021-07-29,4,SMS,9,2024-01-18,21962,6485,37,593.57,Yes
4,C005,Karan Mehta,53,F,Bengaluru,Gold,2020-10-03,1,Email,5,2024-05-30,75991,4426,87,873.46,No

In [ ]:
# marketing_analytics_copy shape
marketing_analytics_copy.shape

(200, 16)

In [ ]:
# column names
marketing_analytics_copy.columns

Index(['Customer_ID', 'Name', 'Age', 'Gender', 'Location', 'Membership_Tier',
       'First_Visit_Date', 'Avg_Monthly_Visits', 'Communication_Preference',
       'NPS_Score', 'Last_Purchase_Date', 'Total_Spend (₹)',
       'Marketing_Spend (₹)', 'Purchases_Last_12M', 'Avg_Order_Value (₹)',
       'Campaign_Responded'],
      dtype='object')

In [ ]:
# import libraries
from datetime import date
from dateutil.relativedelta import relativedelta

In [ ]:
# change the datatype of the column dates
marketing_analytics_copy['First_Visit_Date'] = pd.to_datetime(marketing_analytics_copy['First_Visit_Date'])
marketing_analytics_copy['Last_Purchase_Date'] = pd.to_datetime(marketing_analytics_copy['Last_Purchase_Date'])

In [ ]:
marketing_analytics_copy.dtypes

Customer_ID                         object
Name                                object
Age                                  int64
Gender                              object
Location                            object
Membership_Tier                     object
First_Visit_Date            datetime64[ns]
Avg_Monthly_Visits                   int64
Communication_Preference            object
NPS_Score                            int64
Last_Purchase_Date          datetime64[ns]
Total_Spend (₹)                      int64
Marketing_Spend (₹)                  int64
Purchases_Last_12M                   int64
Avg_Order_Value (₹)                float64
Campaign_Responded                  object
dtype: object

In [ ]:
marketing_analytics_copy['Customer_Lifespan_Years'] = round((marketing_analytics_copy['Last_Purchase_Date'] - marketing_analytics_copy['First_Visit_Date']).dt.days / 365,1)

In [ ]:
marketing_analytics_copy.shape

(200, 17)

In [ ]:
marketing_analytics_copy['Customer_Lifespan_Years'].head()

0    2.2
1    0.3
2    3.0
3    2.5
4    3.7
Name: Customer_Lifespan_Years, dtype: float64

In [ ]:
# Calculate the Customer Lifetime Value
marketing_analytics_copy['Customer_Lifetime_Value'] = marketing_analytics_copy['Customer_Lifespan_Years'] * marketing_analytics_copy['Avg_Order_Value (₹)'] * marketing_analytics_copy['Purchases_Last_12M']

In [ ]:
# See the customers with highest CLV
marketing_analytics_copy.sort_values(by='Customer_Lifetime_Value', ascending=False).head()

,Customer_ID,Name,Age,Gender,Location,Membership_Tier,First_Visit_Date,Avg_Monthly_Visits,Communication_Preference,NPS_Score,Last_Purchase_Date,Total_Spend (₹),Marketing_Spend (₹),Purchases_Last_12M,Avg_Order_Value (₹),Campaign_Responded,Customer_Lifespan_Years,Customer_Lifetime_Value
75,C076,Pooja Joshi,58,F,Delhi,Gold,2020-06-05,4,Email,2,2024-05-05,78771,9851,59,1335.10,No,3.9,307206.510
36,C037,Rakesh Roy,30,M,Bengaluru,Silver,2020-06-09,6,Email,5,2024-07-14,74249,7270,39,1903.82,Yes,4.1,304420.818
14,C015,Sneha Verma,38,F,Delhi,Gold,2020-06-08,7,WhatsApp,7,2024-06-03,71935,3761,71,1013.17,Yes,4.0,287740.280
124,C125,Arjun Joshi,41,M,Delhi,Bronze,2020-07-18,7,WhatsApp,9,2024-03-28,76667,6109,59,1299.44,Yes,3.7,283667.752
4,C005,Karan Mehta,53,F,Bengaluru,Gold,2020-10-03,1,Email,5,2024-05-30,75991,4426,87,873.46,No,3.7,281166.774

In [ ]:
# which communication preference is most used
marketing_analytics_copy['Communication_Preference'].head(10).value_counts()

Communication_Preference
SMS         5
Email       3
WhatsApp    2
Name: count, dtype: int64

In [ ]:
# Net Promotor Score -> Promoters, Detractors and Passives

# Count Promoters (NPS_Score >= 9)
promoters_count = marketing_analytics_copy[marketing_analytics_copy['NPS_Score'] >= 9].shape[0]
print(f"The Count of Promoters are: {promoters_count}")

# Count Passives (NPS_Score >= 7 and NPS_Score <= 8)
passives_count = marketing_analytics_copy[(marketing_analytics_copy['NPS_Score'] >= 7) & (marketing_analytics_copy['NPS_Score'] <= 8)].shape[0]
print(f"The count of Passives are: {passives_count}")

# Count Detractors
detractors_count= marketing_analytics_copy[(marketing_analytics_copy['NPS_Score'] <=6) & (marketing['NPS_Score'] >= 0)].shape[0]
print(f"The count of Detractors are: {detractors_count}")

The Count of Promoters are: 44
The count of Passives are: 28
The count of Detractors are: 128

In [ ]:
 # NPS
(44 - 128)/200 * 100

-42.0